server:
  port: 8089
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/product_db
    username: postgres
    password: root
  jpa:
    hibernate.ddl-auto: update
  application:
    name: product-service
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true