spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/user_db
    username: postgres
    password: root
  jpa:
    hibernate.ddl-auto: update
  application:
    name: user-service
  mvc:
    path match:
      matching-strategy: ANT_PATH_MATCHER

server:
  port: 8081
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
logging:
  level:
    '[org.springframework.cloud.gateway]': TRACE
