
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/login_db
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
  application:
    name: login-service
server:
  port: 8086